### ISSUE TITLE
Command issue

### ISSUE THREAD

**Issue by sscholle** [DanielHabenicht/AzurePipelines-sentry-cli#191]
```
==============================================================================
Task         : Sentry CLI Freestyle
Description  : Task for running the sentry CLI (1.0.5)
Version      : 1.0.5
Author       : Daniel Habenicht
Help         : 
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" run sentry --[MY COMMAND]"
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\Tools\DevOps\Agent\_work\1\s\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Tools\DevOps\Agent\_work\1\s\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I have a feeling this plugin doesn't work any longer. Also the UI looks different than in your screenshot.

![Screenshot 2021-08-06 094212](https://user-images.githubusercontent.com/2486065/128475336-eda1ac7d-cadf-4533-9081-ff3cf2d89ee3.png)

---

Can you provide a working example:
1. samples on how to 'login'
2. sample yaml file for azure pipeline

**Comment by NicolasDionB** [comment]
Wow this has been posted a long time ago, I'm facing the same issue. Has any one cracked this one?

**Comment by DanielHabenicht** [comment]
Sorry, I haven't used this in along time. I will probably mark this package as deprecated.

**Comment by sscholle** [comment]
Thanks for confirming.
